site_name: CloudSlang Documentation
site_url: http://cloudslang.io
repo_url: https://github.com/cloudslang
theme: readthedocs
pages:
  - 'Overview':
    - 'The CloudSlang Project': 'index.md'
    - 'Get Started': 'get_started.md'
    - 'Next Steps': 'next_steps.md'
  - 'CloudSlang':
    - 'Hello World Example': 'hello_world.md'
    - 'Tutorial': 'tutorial.md'
    - 'YAML Overview': 'yaml_overview.md'
    - 'DSL Reference': 'cloudslang_dsl_reference.md'
    - 'Examples': 'cloudslang_examples.md'
    - 'Tests': 'cloudslang_tests.md'
    - 'Best Practices': 'cloudslang_best_practices.md'
    - 'CLI': 'cloudslang_cli.md'
    - 'Build Tool': 'cloudslang_build_tool.md'
    - 'Sublime Integration': 'sublime_integration.md'
  - 'Developer':
    - 'Overview': 'developer_overview.md'
    - 'CloudSlang': 'developer_cloudslang.md'
    - 'CloudSlang Orchestration Engine': 'developer_score.md'
    - 'Architecture': 'developer_architecture.md'
    - 'Contributions': 'developer_contribution.md'
  - 'Tutorial':
    - '1: Introduction and Setup': 'tutorial\01_lesson.md'
    - '2: First Operation': 'tutorial\02_lesson.md'
    - '3: First Flow': 'tutorial\03_lesson.md'
    - '4: Outputs and Results': 'tutorial\04_lesson.md'
    - '5: Default Navigation': 'tutorial\05_lesson.md'
    - '6: Handling Failure Results': 'tutorial\06_lesson.md'
    - '7: Custom Navigation': 'tutorial\07_lesson.md'
    - '8: Input Parameters': 'tutorial\08_lesson.md'
    - '9: Subflows': 'tutorial\09_lesson.md'
    - '10: For Loop': 'tutorial\10_lesson.md'
    - '11: Loop Aggregation': 'tutorial\11_lesson.md'
    - '12: Existing Content': 'tutorial\12_lesson.md'
    - '13: System Properties': 'tutorial\13_lesson.md'
    - '14: 3rd Party Python Packages': 'tutorial\14_lesson.md'
    - '15: Asynchronous Loop': 'tutorial\15_lesson.md'


