version: 2

jobs:
  build:
    docker:
      -image: circleci/openjdk:8-jdk-browsers

    general:
      artifacts:
        - "./cslang-builder/logs/builder.log"

    test:
      pre:
        - >
          wget https://github.com/CloudSlang/cloud-slang/releases/download/cloudslang-1.0.18/cslang-builder.zip
          && unzip cslang-builder.zip
          && chmod +x cslang-builder/bin/cslang-builder
      override: # compile ./code directory
        - ./cslang-builder/bin/cslang-builder -cr ./code -ts !default -cov
